Sentry integration
keploy/vscode-extension pull request #38
Opened 2024-09-09 08:31 UTC by khareyash05

2024-09-19 06:55 UTC, shivamsouravjha requested changes
seems like these are just error catchers, these won't give much information.

Please refer to https://github.com/getsentry/sentry-vscode/tree/master/src project for standard code practices which can help us obtain more information about the scenarios of error.

2024-09-19 06:55 UTC, shivamsouravjha commented on src/OneClickInstall.ts
not used

2024-09-19 06:55 UTC, shivamsouravjha commented on src/SignIn.ts
> +        }).listen(3000); // Change the port if needed
take a pull of branch

2024-09-30 09:23 UTC, shivamsouravjha commented
fix the breaking pipelines please https://github.com/keploy/vscode-extension/actions/runs/11099298022/job/30833306614?pr=38

2024-10-08 06:27 UTC, khareyash05 commented
@shivamsouravjha Fixed the breaking pipelines

2024-10-08 07:14 UTC, khareyash05 commented
![Screenshot 2024-09-25 at 00 07 44](https://github.com/user-attachments/assets/eabd800c-b89c-43e8-a986-137605c674d3)

2025-04-18 08:34 UTC, slayerjain commented
@khareyash05 is this relevant?

2025-04-18 10:00 UTC, khareyash05 commented
NOt relevant right now! As we have introduced traces directly, although will follow up

2025-04-25 15:58 UTC, closed without merging