chore:fixing sign-in and removed jwt logs
keploy/vscode-extension pull request #43
Opened 2024-09-13 07:00 UTC by Aditya-eddy

when the user's logs in. After referesh it's logs out. This or corrects this.

2024-09-13 10:02 UTC, khareyash05 approved these changes
LGTM!

2024-09-16 10:22 UTC, khareyash05 commented on package-lock.json
Revert this change, no need of version change, maybe try updating your branch with main

2024-09-16 10:23 UTC, khareyash05 commented on src/SignIn.ts
Address the semicolon issues, will cause havoc later while reviewing bigger PR's

2024-09-16 10:28 UTC, khareyash05 reviewed
Fix these and we are GTG!

2024-09-16 10:29 UTC, khareyash05 requested changes
Fix these and we are GTG!

2024-09-16 13:45 UTC, Aditya-eddy commented on src/SignIn.ts
removed the semicolons.

2024-09-17 13:34 UTC, Aditya-eddy commented on package-lock.json
done.

2024-09-17 13:36 UTC, khareyash05 commented on src/extension.ts
> +        console.log("accessToken is verfied user us logged in");
unecessary log

2024-09-18 06:05 UTC, khareyash05 commented
Not able to work on Arc browser limitations(will have to fix it soon), @Aditya-eddy if you could attach a video that would be great

2024-09-18 07:39 UTC, khareyash05 approved these changes
LGTM!

2024-09-18 08:39 UTC, merged